services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=elabodeal
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - maildev
  celery_worker:
    command: sh -c "celery -A elabodeal worker -l info -E"
    image: elabodeal-app
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - postgres
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
