version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=elabodeal
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/usr/bin/app
    ports:
      - "8000:8000"
    depends_on:
      - db
